### ISSUE TITLE
Slightly ambiguous about how to process a request with a bad path

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-ip#100]
I'll just use a single example here because I think it makes it easier to express my point but the problems might be wider 

The URI template may include a `ipproto` variable, which is later defined in https://www.ietf.org/archive/id/draft-ietf-masque-connect-ip-05.html#section-4.5 as `ipproto = 1*3DIGIT / "*"`. The value can only be between 0 through 255, I presume this is a decimal value.

What is expected to happen if I send some bad values like:

* `:path = /proxy?ipproto=-1`
* `:path = /proxy?ipproto=abc`
* `:path = /proxy?ipproto=256`
* `:path = /proxy?ipproto=1234`

I presume that the recipient would reject the request with a bad path, by virtue of applying the requirement in section 4 that :path SHALL NOT be empty *and* following the expansion requirements in Section 3 *and* following those requirements on to Section 4.5. That's a lot of hops to get things right. Is there any easier way to present these?

**Comment by DavidSchinazi** [comment]
Agreed, we need better text to specify server handling. For example, we don't currently explicitly that the server has to percent-decode these variables (but we say they have to be percent-encoded). When we add new text about how to extract the variables and decode them, let's also say that the server has to validate that they match requirements and has treat the request as malformed if they don't

**Comment by tfpauly** [comment]
@DavidSchinazi can you write up some text?
