### ISSUE TITLE
ipproto is in the range of 0-255 but capsules can only use 4 or 6

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-ip#101]
The `IP version` field in the three new capusles says it must be a value of 4 or 6. So I don't understand why it is allowed to send any other value in `ipproto` field.

If "The client can choose to restrict a given request to a specific IP prefix or IP protocol by adding parameters to its request." and it picks `10`, then none of these capsules can be used?

**Comment by asedeno** [comment]
`IP version` is IPv4 or IPv6
`iproto` is  TCP, UDP, ICMP, SCTP, etc.
https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml

**Comment by LPardue** [comment]
hah yeah I just realized this and came to close the issue. Apologies for the noise and thanks for the pointer
