### ISSUE TITLE
What are the expectations for a receiver of capsules that break the MUSTs

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-ip#102]
There's a lot of rules about how the contents of fields should be populated. If I run an IP proxy and I receive some clearly broken capsules, what am I expected to do?  It would be nice to be a lot clearer here, especially about whether it is a request-level error or a connection-level one.

**Comment by DavidSchinazi** [comment]
This is pretty clearly specified in [RFC 9297's Capsule Protocol Error Handling section](https://www.rfc-editor.org/rfc/rfc9297.html#section-3.3) but adding an explicit reference to that sounds like a good idea

**Comment by LPardue** [comment]
:+1:  A link to that section in each capsules defintion, or clearly at the top in 4.6, would alleviate any doubt.

**Comment by tfpauly** [comment]
Whoops, committed to main for that one...

**Comment by DavidSchinazi** [comment]
For future reference this was fixed by 71dd8d21097a82b730b68d77bd55c0ed1fc91273

**Comment by LPardue** [comment]
Thanks lgtm
