### ISSUE TITLE
Does the order of address requests in ADDRESS_REQUEST or address assigned's in ADDRESS_ASSIGN have semantics?

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-ip#104]
I'm going to guess that order is not significant. But imagine that an endpoint would only honor a request for N addresses but the requester asks for N+Y. The endpoint has to pick a subset somehow.

**Comment by achernya** [comment]
What do you mean by "is the list ... significant"? I don't understand the comment about subsetting either --- if you ask for N+Y addresses and get back only N, you have N usable addresses (ranges)

**Comment by LPardue** [comment]
How does the other end decide the which N to pick? Without declaring if the request order is significant, then there can be no expectations of behaviour and we might find interop problems if assumptions don't align.

**Comment by achernya** [comment]
If you request, say, 4 specific addresses, and the other side can satisfy 3 of the requests because they're still available, it will include those 3. It's implementation-defined it if wants to provide a 4th address that is not the one you requested, or NAK it. However at no point in time was order significant --- you asked for _all_ of these addresses, not _any_ of these addresses.

**Comment by asedeno** [comment]
Friendly amendment: it may include those 3. It could also choose to only assign one, or a different address entirely if the implementation was so inclined.

**Comment by achernya** [comment]
You are pedantically correct :). I was trying to give a specific worked example.

**Comment by LPardue** [comment]
This design seems reasonable. It might help to state clearly somewhere that the value of the request ID has no significance other than as a unique handle, and that the ordering of `Requested Address` and `Assigned Address` in a single capsule has no significance. This is in contrast to the ROUTE_ADVERTISEMENT where the ordering of things is very significant.

**Comment by achernya** [comment]
That's a good suggestion Lucas.

**Comment by DavidSchinazi** [comment]
My intention when writing this was for the order in the lists to not carry semantics, and similarly for the request ID to only exist for unicity. We should spell that out clearly.

One thing we could do however, is saying that request IDs in ADDRESS_REQUEST MUST be increasing, to make duplicate detection easier on the receiver. If we do it, it adds a constraint on the sender and means that the receiver will check, while if we don't add the constraint then receivers won't bother to check. Any thoughts on this point?

**Comment by LPardue** [comment]
I have no strong feeling about the potential to add such rules.

**Comment by tfpauly** [comment]
@achernya can you propose text here?
