### ISSUE TITLE
Potential DoS vector via spamming ADDRESS_REQUEST

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-ip#106]
IIUC the recipient of an ADDRESS_REQUEST has to respond one way or another, using ADDRESS_ASSIGN. Via #96, it is possible to reject a request and send a "null response" back. 

Per ADDRESS_ASSIGN

> If an ADDRESS_ASSIGN capsule does not contain an address that was previously transmitted in another ADDRESS_ASSIGN capsule, that indicates that the address has been removed.

Technically, the address was never given, so sending a "null address" just once and then never sending it again is probably a good move - it limits the commitment to remember full details and reduces capsule transfer size. Endpoints that try to send a complete list of addresses in every ADDRESS_ASSIGN, including the null ones, might find they could get aboused, because its a lot simpler to send a short request with a unique request ID, than to respond to it.

Probably nothing needs to change in the protocol but adding some considerations for implementers might be nice.

**Comment by DavidSchinazi** [comment]
That's fair, we should say that the all-zero addresses don't need to be repeated in future capsules
