### ISSUE TITLE
Clarify the IPv6 MTU ping technique?

### ISSUE THREAD

**Issue by jhatala** [ietf-wg-masque/draft-ietf-masque-connect-ip#119]
> IP proxying endpoints can also send ICMPv6 echo requests with 1232 bytes of data to ascertain the link MTU and tear down the tunnel if they do not receive a response. Unless endpoints have an out of band means of guaranteeing that the previous techniques is sufficient, they MUST use this method.

Which IPv6 address is the Client pinging through the tunnel?  The Client knows which source address(es) it can use (from the ADDRESS_ASSIGN(s) that it has received), but not necessarily a good destination address.  When ROUTE_ADVERTISEMENT are networks, it is not clear which hosts if any on those networks are pingable.  In the flow forwarding case, there is a clear target host, but do we want to require the target to respond to ICMPv6 echo request pings lest it be unreachable on any protocol over connect-ip?

Perhaps the destination address for these pings should be a special address on which the IP Proxy itself is required to respond to ICMPv6 echo requests through the tunnel?

**Comment by tfpauly** [comment]
Good question! @DavidSchinazi thoughts?

**Comment by achernya** [comment]
This was intended to be the link-local address(es)

**Comment by DavidSchinazi** [comment]
Good catch. I'll write a PR suggesting to use the link-local all-nodes multicast address if the peer's address is unknown
