### ISSUE TITLE
IP Address Range overlap prevention when IP Protocol is 0 vs non-0.

### ISSUE THREAD

**Issue by jhatala** [ietf-wg-masque/draft-ietf-masque-connect-ip#120]
> If multiple ranges using the same IP protocol were to overlap, some routing table implementations might reject them. To prevent overlap, the ranges are ordered; this places the burden on the sender and makes verification by the receiver much simpler. If an IP Address Range A precedes an IP address range B in the same ROUTE_ADVERTISEMENT capsule, they MUST follow these requirements:
> * IP Version of A MUST be less than or equal than IP Version of B
> * If the IP Version of A and B are equal, the IP Protocol of A MUST be less than or equal than IP Protocol of B.
> * If the IP Version and IP Protocol of A and B are both equal, the End IP Address of A MUST be strictly less than the Start IP Address of B.

Say for example that A and B have the same IP Version and they have the same or overlapping Start IP Address / End IP Address ranges.  A's IP Protocol is zero (the wildcard) whereas B's is non-zero.  That causes a weird kind of overlap even though all the requirements are followed.  Is it worth disallowing in the spec?

**Comment by tfpauly** [comment]
Earlier in this section, the version is defined as such:

> IP Version of this range, encoded as an unsigned 8-bit integer. MUST be either 4 or 6.

I think then this is OK, since zeros aren't allowed in route advertisements.

@jhatala that sound OK?

**Comment by jhatala** [comment]
The IP Verson cannot be zero in the ROUTE_ADVERTISEMENT, but the IP Protocol can:

> IP Protocol:
> The Internet Protocol Number for traffic that can be sent to this range, encoded as an unsigned 8-bit integer. If the value is 0, all protocols are allowed.

The following ROUTE_ADVERTISEMENT follows the requirements (the IP Protocol of A is lower than the IP Protocol of B), yet there is an overlap:

```
ROUTE_ADVERTISEMENT Capsule {
  Type = ROUTE_ADVERTISEMENT,
  Length = ... ,
  IP Address Range {
    IP Version       = 4,
    Start IP Address = 192.168.0.0,
    End IP Address   = 192.168.0.255,
    IP Protocol      = 0
  }
  IP Address Range {
    IP Version       = 4,
    Start IP Address = 192.168.0.0,
    End IP Address   = 192.168.0.255,
    IP Protocol      = 17
  }
}
```

**Comment by tfpauly** [comment]
Oh, I see, I misread. I do think that it makes sense to put the wildcard first — so 0 shows up before others. And then the more specific protocol rules can potentially have different ranges.

I still think this is acceptable to leave as-is.
