### ISSUE TITLE
List comments from Vinny

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-masque/draft-ietf-masque-connect-ip#126]
Section 4.6 has a minor issue as the IANA registry mixes IPv6 extension header with layer-4 headers.
       It should also specify the use of RFC 5952 for representing IPv6 addresses. However, this can be ignored for now.
 
Section 4.7.1 unsure whether "IP Version" field is useful as it can be derived from "IP Address" length/notation, also not critical but perhaps this would reduce unnecessary information.
 
There is also a minimum 68-byte MTU for IPv4 ;-)  - not sure that is important, but wanted to share.
 
The recursive DNS server info (found in RA and DHCP), is not present.  Was this an intentional decision or perhaps something that was not considered for some reason?
 
There is no discussion of link-local addresses / ULA (I would expect both end of the 'tunnel' to have link-local addresses), or link-local multicast (e.g., ff02::1). 
Or perhaps the IP proxy send an IPv6 RA ? or should be prevented from sending one ? Should IP proxy reply to ff02::2 (all link-local routers), ...

**Comment by DavidSchinazi** [comment]
Closing this issue in favor of more specific ones
