### ISSUE TITLE
Optional signal reminder

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-masque/draft-ietf-masque-connect-ip#134]
From @martinduke 

> (S4) It might be useful to have a non-normative reminder (with references) that the Capsule-Protocol header is an optional signal to intermediaries. It appears in the example but there's no guide to look it up in RFC 9297.

**Comment by martinduke** [comment]
I still think something to effect of "The capsule-protocol header in these examples is defined in [RFC9297]" would be useful, but I won't insist. Close this issue if you still disagree.

**Comment by tfpauly** [comment]
I think we're OK to close this
