### ISSUE TITLE
Address use conditions

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-masque/draft-ietf-masque-connect-ip#135]
From @martinduke 

> (S4.7) Somewhere around this section, please clearly state the conditions under which an endpoint can use source and destination IPs in its packets, without fear of being dropped by the peer due to an improper address. For example,
> - Using any src or dst IP address is not a protocol violation, but may be dropped by the peer.
> - Using a SRC IP provided by ADDRESS_ASSIGN is always valid
> - Using a DST IP provided by ROUTE_ADVERTISEMENT, or listed as a literal IP in a CONNECT request that is accepted is always valid.
> ... or whatever your intent is, this is what I'm gleaning from the draft.

**Comment by DavidSchinazi** [comment]
This is IP networking, so there is no notion of "fear of being dropped". Any IP link or router can drop any packet any time for any reason. I wrote a PR #141 to clarify this.

**Comment by DavidSchinazi** [comment]
No, that's not how IP networks work. Let's take the example of DHCP: a client attaches to a new network and asks for an address. The DHCP server assigns an IP to the client. The client often sends from that address, but that assignment does not represent any assurances with regards to delivery, it represents unicity. On my home network I have DHCP but also machines with static addresses - when I get address X via DHCP, I have absolutely no assurance that sending with that source address is more likely to succeed than with this static address. Whether packets gets through is a matter of either (a) policy or (b) addressing architecture - both of which were decided out of scope during the WG consensus process for draft-ietf-masque-ip-proxy-reqs, see [here](https://www.ietf.org/archive/id/draft-ietf-masque-ip-proxy-reqs-03.html#name-non-requirements).

All this to say, I understand what you're asking for - but it's squarely out of scope

**Comment by martinduke** [comment]
"I have absolutely no assurance that sending with that source address is more likely to succeed than with this static address."

"assurance" and "more likely" are weird things to have in the same sentence -- anything dealing with likelihood is by definition not assured.

Your flattening of the distinction between addresses the sender picks out of the air and those in ADDRESS_ASSIGNED and ROUTE_ADVERTISEMENT makes me wonder what the point of those capsules are. ADDRESS_ASSIGNED at least means "I will try to deliver packets to you if they have this destination IP", but what does ROUTE_ADVERTISEMENT mean if not "you have a somewhat better chance of delivering these than a randomly picked destination IP?"

And whatever ROUTE_ADVERTISEMENT means, is a 200 on CONNECT to a literal IP equivalent, or do they carry different semantics?

**Comment by DavidSchinazi** [comment]
These capsules exchange configuration data. The recipient is free to choose to apply said configuration, or ignore it. To answer your specific question: yes - if you are a split-tunnel VPN client, you'll install any routes from ROUTE_ADVERTISEMENT into your routing table. But in a separate scenario if you're just trying to get a point-to-point link, you're going to ignore a ROUTE_ADVERTISEMENT telling you the whole world is routable.

Taking a few steps back: what change would you like to see in the draft that is not covered by #141?

**Comment by martinduke** [comment]
OK, after a higher-bandwidth discussion, where I went wrong is with this sentence in S4.7.3:

"Upon receiving the ROUTE_ADVERTISEMENT capsule, an endpoint MAY start routing IP packets in these ranges to its peer."

This implies that an endpoint should not send before this, which is not the intent.

@DavidSchinazi and I agreed that this sentence should be deleted or changed. I recommended some sort of alternative sentence(s) in this section that clearly stated the purpose of this capsule, perhaps something that ends with "for the use cases where clients require it"

**Comment by DavidSchinazi** [comment]
@martinduke I wrote up a fix for that last point as #142. That's what we initially intended and avoid the unintended implication
