### ISSUE TITLE
Proxy capsule handling requirements

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-masque/draft-ietf-masque-connect-ip#136]
From @martinduke:

> (S6) What if a capsule IP address range includes a link-local address? It's not a protocol violation  since /0 is legal. Does the receiver simply omit link-local addresses from a broader range when picking an address?
> 
> (S6) It's interesting to say that the sender MUST reset the stream if the PMTU isn't big enough for DATAGRAM. I vaguely recall an extended discussion on this, but a MUST sets up weird incentives to use Capsules instead of datagram. (No action item on this bullet, I think).

**Comment by DavidSchinazi** [comment]
> (S6) What if a capsule IP address range includes a link-local address? It's not a protocol violation  since /0 is legal. Does the receiver simply omit link-local addresses from a broader range when picking an address?

Link-local addresses are valid, why would they not be?

> (S6) It's interesting to say that the sender MUST reset the stream if the PMTU isn't big enough for DATAGRAM. I vaguely recall an extended discussion on this, but a MUST sets up weird incentives to use Capsules instead of datagram. (No action item on this bullet, I think).

This was the consensus of the editors and then of the WG. I agree with you about incentives, but this was deemed better than any alternative proposed at the time.

**Comment by martinduke** [comment]
On the second point, OK, I figured as much.

The first point is triggered by (S6):
"Implementers need to ensure that they do not forward any link-local traffic onto a different interface than the one it was received on. IP proxies also need to properly reply to packets destined to link-local multicast addresses."

I'm having a little trouble reasoning about this, but is it allowed for a proxy to send ADDRESS_ASSIGN containing a link-local address? Only if the MASQUE connection is on the same physical interface as the address? Or is a MASQUE connection a virtual interface?

Similarly, are there conditions where a client could send an IP packet addressed to a link-local address? If so, would this be forwarded out the "internet end" of the proxy?

I'm not convinced there's a problem here, but I'm confused.

**Comment by DavidSchinazi** [comment]
> is it allowed for a proxy to send ADDRESS_ASSIGN containing a link-local address?

Yes, why would it not be?

> Only if the MASQUE connection is on the same physical interface as the address?

No no no - these addresses are inside the tunnel.

> Or is a MASQUE connection a virtual interface?

A MASQUE connection is a virtual interface, just like IPsec, WireGuard, OpenVPN, etc. "Virtual interface" is not a well-defined concept as far as RFCs go, but yeah it's an interface that isn't a physical cable or radio.

> Similarly, are there conditions where a client could send an IP packet addressed to a link-local address?

Yes. So the use for this is the traditional scenario where both IP proxying endpoints have link-local addresses, then they can use them to communicate between one another. 

> If so, would this be forwarded out the "internet end" of the proxy?

No, link-local traffic is by definition local to the link. Those packets cannot be *forwarded* onto another interface. They can only be destined to the peer.

**Comment by martinduke** [comment]
After further high-bandwidth discussion, I believe the design covers all the bases. We agreed that the following two changes are best:
(1) Both connect-IP endpoints need to reply to link-layer multicast, not just the proxy.
(2) change the requirement about not forwarding link-local IPs over different interfaces (which opens up a useless what-is-an-interface discussion) with clearer language like "don't forward beyond that IP tunnel" or "beyond the HTTP stream", etc.
