### ISSUE TITLE
Missing bits in example

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-masque/draft-ietf-masque-connect-ip#138]
From @martinduke:

> (S8.4) The example doesn't include a target hostname, which makes it hard to understand what IP address the proxy is putting in ROUTE_ADVERTISEMENT. I think this might just be an omission. If it's meant to illustrate some subtle point about the design, it's over my head entirely.

**Comment by DavidSchinazi** [comment]
Good point, this was a mistake. Fixing via #140
