### ISSUE TITLE
Should there be an ADDRESS_RELEASE capsule?

### ISSUE THREAD

**Issue by ehaydenr** [ietf-wg-masque/draft-ietf-masque-connect-ip#143]
The draft supports soliciting additional addresses via ADDRESS_REQUEST capsules, but there's no way for a client to release an address other than closing the stream.

Consider the "Remote Access VPN" example: a client is using connect-ip to access subnet C. At some time later, the client wants to access some other subnet D. It uses subnet D for a while, but now it no longer needs it. The client has no way to release the address(es) for subnet D while retaining address(es) for subnet C.

This is less of a concern for clients because worst case the client just holds all addresses until it's done with all addresses. For proxies, depending on how common the above scenario is, this may or may not result in address exhaustion that could have been avoided.

Regardless of how likely the above scenario is, given how easy I suspect it would be to implement, I wonder if an ADDRESS_RELEASE capsule makes sense for the sake of completeness.

**Comment by DavidSchinazi** [comment]
Do you have a specific use case for this? Our general mindset has been to avoid scope creep and punt extra features to extensions.

**Comment by ehaydenr** [comment]
I do not have a specific use case for this. It seems natural to me that with a way to solicit new addresses via capsules that there would be a way to release addresses via capsules as well. I'm not familiar enough to say whether this is actually useful in practice.

**Comment by achernya** [comment]
This seems like a reasonable future extension, but not something we need in the core draft for it to be usable. This effect could be achieved by creating a new CONNECT-IP session and terminating the previous one.

**Comment by ehaydenr** [comment]
Thanks, sounds good
