### ISSUE TITLE
Clarify the conceptual model of router vs link (Tunnel)

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ip#165]
Joe Touch had several comments that related to the document lacking discussion of the conceptual model of the need for a router connected to the link that the tunnel represent and how that interact with the different functions. He had comments on several aspects that would be clearer to explain with that model in place.

1) How MTU of the tunnel interact with the sending of ICMP by the router part and potential refragmentation of IPv4 without DF bit set etc. See Sec 3.2 of draft-ietf-intarea-tunnels for ICMP discussion
2) Clarify that it is the routers forwarding decision that decrements the TTL of the IP packet not the tunnel.
3) Unclarity of the ingress / egress components that appear attached to (possibly virtual) interface. 
      - Such as the target and IPProto parameter is actually traffic filters for the routing decision to forward a packet through a particular tunnel. (Magnus realization from the target discussion)

**Comment by DavidSchinazi** [comment]
I think I now understand Joe's point: this document specifies a (virtual) link with routers attached to it. The IP proxying endpoints both act as routers that are connected by this virtual link. That's why we talk about having them send ICMP. Adding some text to clarify this should help.

**Comment by huitema** [comment]
The issue is that the draft has some text including router functions, such as handling TTL or advertising routing prefixes. I think Joe is correct, and that those don't belong. That's clear for TTL: the IP TTL is handled by the routing function, not be the tunnel, no point specifying it here. The address configuration functions, ICMP generation, etc., are similarly functions for the router or the hosts, maybe sending configuration packets over the tunnel. Maybe cut text and simplify?

**Comment by gloinul** [comment]
So the Connect-IP method do define more than just the establishment of a tunnel. It also defines a signalling protocol for establishing traffic filters for those tunnels. Thus, interacting with the router functionality and also with the address assignment mechanism for those cases where the IP proxying endpoint act as a network gateway with the tunnel as an link to the rest of the network.

**Comment by DavidSchinazi** [comment]
+1 to @gloinul. Implementers of this spec will often implement parts of the router functionality, so it's worth mentioning this in this document. I think we can make everyone happy by splitting the "IP Packet Handling" section into one subsection about the link function and one part about the router function

**Comment by DavidSchinazi** [comment]
I've performed this split in #172
