### ISSUE TITLE
Clarify that IPproto is a traffic filter parameter on the outermost IP header that is to be encapsulated by the tunnel

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ip#166]
From Joe Touch's review

The definition of the IPProto variable is unclear on what level of IP header it applies. It can be missunderstood apply as a filter to the outermost IP header at all, while it is filtering the next header field in that outermost IP packet. And that it might in some cases apply to both IPv4 and IPv6 packets depending on target and Address assignments.

**Comment by DavidSchinazi** [comment]
The goal was to filter the next header field of the outermost encapsulated IP packet, with the exception of skipping through IPv6 extension headers. We can tighten the text to clarify this. Here are some examples, some takem from Joe's latest email:

* ipproto=17 (UDP)
  * MATCHES IPv4 containing UDP
  * MATCHES IPv6 containing UDP
  * MATCHES IPv6 containing v6 routing header containing UDP
  * DOES NOT MATCH IPv4 containing IPv4 containing UDP
  * DOES NOT MATCH IPv4 containing IPv6 containing UDP
  * DOES NOT MATCH IPv4 containing IPsec containing IPv4 containing UDP
* ipproto=41 (IPv6 encapsulation)
  * DOES NOT MATCH IPv4 containing UDP
  * DOES NOT MATCH IPv6 containing UDP
  * DOES NOT MATCH IPv6 containing v6 routing header containing UDP
  * DOES NOT MATCH IPv4 containing IPv4 containing UDP
  * MATCHES IPv4 containing IPv6 containing UDP
  * MATCHES IPv6 containing IPv6 containing UDP
  * DOES NOT MATCH IPv4 containing IPsec containing IPv4 containing UDP
  * MATCHES IPv6 containing IPsec containing IPv6 containing UDP
