### ISSUE TITLE
Go through usage of client and server vs IP proxying endpoint

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ip#167]
Joe Touch had a comment about the use of client and server.

This appear to be correct in some cases where the HTTP client and server roles are referred to. But there might be others that should be IP proxying endpoint as the behaviour is not related to if the HTTP client or server role. 

So we should review all to verify the correctness.

**Comment by DavidSchinazi** [comment]
From looking at Joe's examples, the spec is correct:

> The abstract, which talks about the server acting a proxy but not the client:
>> ...this document defines a protocol that allows an HTTP client to create an IP tunnel through an HTTP server that acts as an IP proxy

That's right - the client initiates the tunnel

> Sec 2 definitions, again focusing on the behavior of the server, not the client:
>> In this document, we use the term "IP proxy" to refer to the HTTP server that responds to the IP proxying request.

This is also correct, it defines the term "IP proxy" which is an HTTP server

> Sec 7 describes clients sending packets to servers; I could not easily locate the converse:

Sec 6 does speak in terms of endpoints, so we're also good there.

I propose we close this with no action unless you have specific changes in mind Magnus.

**Comment by gloinul** [comment]
So I think we maybe want to define IP Proxying endpoint in the terminolgy in section 2. Because currently its first usage is in Performance section. 
There are also at least one usage of "client and IP proxy" that can be replaced by IP proxying endpoint. The case I spotted was in the first paragraph in 11.2 ECN Considerations. There are additional in 11.3. So I think we should go over the document and look at this.

**Comment by DavidSchinazi** [comment]
That's a good point. Explicitly defining "IP proxying endpoints" in section 2 is a good idea

**Comment by DavidSchinazi** [comment]
OK I reviewed our uses of those words and added the definition via https://github.com/ietf-wg-masque/draft-ietf-masque-connect-ip/pull/171
