### ISSUE TITLE
Treating differentiated services equally?

### ISSUE THREAD

**Issue by bbriscoe** [ietf-wg-masque/draft-ietf-masque-connect-ip#173]
https://github.com/ietf-wg-masque/draft-ietf-masque-connect-ip/blob/18a5795636aedd49b5439f801532a0609f593162/draft-ietf-masque-connect-ip.md?plain=1#L1396

I think this means treated equally by the network (but it might mean treated equally by the HTTP proxy?).
So first of all, it would be clearer not to write this in the passive.

Whatever, it is counter to differentiated services to treat all packets equally regardless of their DSCP. Assured Forwarding (AF) in Diffserv is designed on the premise of a single congestion control behaviour across a ranked set of DSCPs. So the statement that "the tunneled packets need to be treated equally regardless of their DSCP markings to not disrupt the congestion controller." seems to imply an incorrect or unorthodox understanding of how congestion control and Diffserv interact.

> In this scenario, the IP proxying endpoint MUST NOT copy the DSCP field from the inner IP header to the outer IP header of the packet carrying this packet. Instead, an application would need to use separate connections to the proxy, one for each DSCP. 

It would be OK to use separate connections, one for each DSCP. But it is surely wrong to say "the IP proxying endpoint MUST NOT copy the DSCP field from the inner IP header to the outer IP header." How would network nodes apply differentiated forwarding treatment if the DSCP is not in the outer? Instead, surely all that is necessary here is to cite RFC2983, which defines two modes (uniform and pipe) that the operator can choose between. With one the DSCP is copied to the outer, and in the other it isn't. Otherwise, the present wording applies a blanket  ban on Diffserv across all ip-connect tunnels, and the only reason seems to be a misunderstanding.

I think the problem here is making DSCP copying conditional on disabling congestion control. I believe DSCP copying should be independent of congestion control. It should only depend on operator policy (per RFC2983). IOW, the requirements in the last para of the Diffserv section are correct, except they can be applied irrespective of congestion-control.

**Comment by mirjak** [comment]
I think generally talking about copying DSCP or other bits from the inner to the outer is not appropriate here as this is not an IP tunnel (only) but a L7 proxy. Thus the tunnel connection is an end-to-end connection from the client to proxy (usually including own cc) and need to be considered rather independent of the inner packets/payload. If you want differential treatment, you can open multiple tunnel connections and use a different DSCPs on each and then you can map the inner traffic to a certain connection based on their DSCP marks, but it not really copying.

**Comment by DavidSchinazi** [comment]
I agree with what @gloinul and @mirjak are saying but I do think @bbriscoe has correctly pointed out that the paragraph could misunderstood. I've written up editorial PR #174 that should clarify the intent. Please take a look.
