### ISSUE TITLE
AUTH48: Use of Successful response

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ip#179]
Section 4.1 contains
"A successful response (as defined in Sections [4.3](https://www.rfc-editor.org/authors/rfc9484.html#resp1) and [4.5](https://www.rfc-editor.org/authors/rfc9484.html#resp23)) indicates that the IP proxy has established an IP tunnel and is willing to proxy IP payloads. Any response other than a successful response indicates that the request has failed; thus, the client MUST abort the request."

First please remember that Section 4.3 (HTTP/1.x) defines 101 as a successful response, while it is 200 for HTTP/2 or HTTP/3.
First I think the second sentence is to harsh and does violate HTTP semantics. Because I don't think a 100 Continue response should case an abort of the request. Also, for HTTP/1.x any 2xx response is per definition successful in HTTP world, but not applicable here. And Section 4.3 is not explicit enough about that.

**Comment by DavidSchinazi** [comment]
Fair point. I've fixed the confusion by replacing "successful response" with "successful IP proxying response", a term that we were already using in other parts of the document. See #182.

**Comment by gloinul** [comment]
Works for me.

**Comment by DavidSchinazi** [comment]
Closed by merging #182
