### ISSUE TITLE
AUTH48: Use of "Fail the request"

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ip#180]
Section 4.6 says:

"IP proxies MAY perform access control using the scoping information provided by the client, i.e., if the client is not authorized to access any of the destinations included in the scope, then the IP proxy can immediately fail the request."

So I don't think it is clear what is meant with a "fail the request" means here. Shouldn't we be more explicit about what response should be, is this a 403 response?

**Comment by DavidSchinazi** [comment]
> So I don't think it is clear what is meant with a "fail the request" means here.

You're right, the HTTP specs use "reject", not "fail". Fixing via #181.

> Shouldn't we be more explicit about what response should be, is this a 403 response?

In HTTP we explicitly do not mandate which status code to use because that could lead clients to expect some values which in turn prevents extensibility.

**Comment by gloinul** [comment]
PR looks good.

**Comment by DavidSchinazi** [comment]
Closed by merged #181
