### ISSUE TITLE
AUTH48: clarify frames per packet

### ISSUE THREAD

**Issue by achernya** [ietf-wg-masque/draft-ietf-masque-connect-ip#184]
Currently section 7.1 Link Operation says "for example, because a QUIC packet can carry two QUIC DATAGRAM frames." This is technically correct, but I think it would be clearer if this said "can carry two or more QUIC DATAGRAM frames", as we are not limited to only one or two frames per QUIC packet.

This is a very minor nit and I am happy to have this issue marked as WONTFIX if the other editors do not think this is worthwhile.

**Comment by DavidSchinazi** [comment]
Closed via #185
