### ISSUE TITLE
Add separate discussion about ICMP handling

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-connect-ip#21]
There might be ICMP messages that are relevant to the proxy and should be handled by the proxy, mainly in flow mode. This needs additional discussion in the draft.

**Comment by achernya** [comment]
Can you please clarify which ICMP messages you think the proxy should be handling and in which operating mode of CONNECT-IP?

**Comment by tfpauly** [comment]
Proposing a separate document for this to go into more detail and solve the problem for various protocols.

**Comment by achernya** [comment]
I don't think we should write our intent to write another document into this document, but we should certainly discuss that when this document is presented at the next meeting.

**Comment by DavidSchinazi** [comment]
Based on the past discussion here and the lack of new evidence, should we close this with no action?

**Comment by tfpauly** [comment]
Yeah, I think it will be another document anyhow. We can close it here.
