### ISSUE TITLE
Consider allowing the target in the HTTP request to be a subnet

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-masque/draft-ietf-masque-connect-ip#22]
Instead of just an address / hostname, could we ask to open a tunnel to a prefix?

**Comment by tfpauly** [comment]
This came up in a discussion—if we let you ask to connect to a specific hostname or address instead of all addresses (as we do today), we wondered if there was any need to connect to a subnet of addresses. This would be for connecting to an IPv6 /64, which is unique enough for a device, and doesn't require needing to assign an IP address exclusively to the client that is issuing the request.

**Comment by DavidSchinazi** [comment]
I'm supportive of adding this if we can come up with an encoding that's not a pain to implement. For example slash with prefix length seems fine to me - the slash would be percent-encoded just like the IPv6 address colons are.

**Comment by gloinul** [comment]
In relation to my just raised issue on source address validation #52 if we add this functionality, I would think that the proxy would need to do destination or source address validation depending on direction of traffic to enforce the signalled aspect.
