### ISSUE TITLE
Explain behavior when handling multiple capsules of a given type

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ip#32]
I think the capsules description needs to be explicit if multiple capsules are allowed. I think there are different considerations depending on what type of capsules are used. 

The authors have already discussed and concluded that multiple route_advertisement will be needed to allow to declare reachability of multiple prefix.

I don''t know if multiple address_assign capsules are allowed. Allowing multiple allows multiple address ranges to be declared. However, that results that we also get the question if one need to withdraw source address prefixes..

**Comment by DavidSchinazi** [comment]
Agreed, multiple capsules of all currently defined capsule types are allowed. For example, multiple ADDRESS_ASSIGN are needed to support a dual-stack tunnel. I'll write a PR.
