### ISSUE TITLE
Proxies SHOULD provide all routes for resolved addresses

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-masque/draft-ietf-masque-connect-ip#37]
We should be clear that when a proxy resolves a hostname, it SHOULD give all results back as routes to the client (unless there is some policy to restrict it).

Credit to @bemasc for proposing this [on the list](https://mailarchive.ietf.org/arch/msg/masque/YebmYEe4m0vGTunTdN3wgGXUNh8/)

**Comment by DavidSchinazi** [comment]
I agree

**Comment by bemasc** [comment]
> Say I ask for the proxy to connect to example.com:443

Nit: there is no port number.

> Am I supposed to assume that this is the result of the DNS lookup?

That's the status quo in this draft for hostname targets.  The implicit signal here doesn't bother me, since it's unambiguous.

I'm also fine with dropping support for DNS targets, although I think it might be useful in some scenarios.
