### ISSUE TITLE
IP address format not specified for "target" parameter. 

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ip#53]
There is no normative specification for the target IP address formats that can be used.

**Comment by DavidSchinazi** [comment]
Agreed, this text could be formalized a bit more. In particular it should mention percent-encoding of colons in IPv6 addresses, and the fact that IPv6 scoped addressing zone identifiers are not supported. We could pull in some of the text from CONNECT-UDP.
