### ISSUE TITLE
We should define a way for target and ipproto to convey "any"

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-connect-ip#55]
As pointed by @gloinul is https://github.com/ietf-wg-masque/draft-ietf-masque-connect-ip/issues/46#issuecomment-1172053375, there is currently no non-empty way to convey "any ipproto" or "any IP address of any address family". That can cause issues when using some path templates. It would be simple to define a non-empty way to convey "any". I propose using `*` for this purpose.

(I wouldn't use ipproto=0 to mean "any ipproto" because 0 means IPv6 Hop-by-Hop Options)

**Comment by tfpauly** [comment]
Yeah, using "*" seems fine here

**Comment by gloinul** [comment]
So I have now attempted to address this is PR #48. Please review.
