### ISSUE TITLE
Unclear responsibility for HTTP intermediaries prevents ensuring IPv6 minimal link MTU

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ip#61]
Even if PR #60 was an improvement to the description of the IPv6 minimal link MTU issue the text still leaves an open issue in that it doesn't make clear which of the endpoints that are responsible for HTTP intermediaries or if is truly both which has another implication. 

So a Connect-IP endpoint will be aware of the HTTP datagram supported MTU and if its HTTP/3 connection can support sending at least 1280 bytes of IPv6 packets without fragmentation. However, if there is two or more HTTP intermediaries in between the client and the server then there are HTTP intermediaries that might have an HTTP/3 connection which has less than 1280 bytes MTU for HTTP datagram payloads in-between the client and server. Thus, arises the issue of how to detect this. 

PR #60 states: 

* if HTTP intermediaries are in use, CONNECT-IP endpoints can enter in an out of
   band agreement with the intermediaries to ensure that endpoints and
   intermediaries pad QUIC INITIAL packets.

From my perspective the big question is how a client or a server knows that there are intermediaries, or the most important aspect, that there are no unknown HTTP intermediaries. To my understanding both the client and the server can potentially bring in HTTP intermediaries unknown to the other part. Thus resulting in a HTTP intermediary to intermediary connection where neither endpoint knows if the requirement is fulfilled. 

Thus my interpretation is that the only way to be sure that it works it to actually execute on the third bullet in the PR:

* CONNECT-IP endpoints can also send ICMPv6 echo requests with 1232 bytes of
   data to ascertain the link MTU and tear down the tunnel if they do not receive
   a response. Unless endpoints have an out of band means of guaranteeing that
   one of the two previous techniques is sufficient, they MUST use this method.

I would also note that this only verifies from the acting endpoint towards its peer, not the reverse path. For that to be verified the peer need to send ICMP probes the other direction. 

Thus, my conclusion is that Connect-IP still don't ensure that the minimal MTU is fulfilled.

**Comment by achernya** [comment]
Isn't the quick-fix to require that the ICMP reply also be 1232 byte sized?

**Comment by gloinul** [comment]
Normally I would say now, as you want to ensure that the reply makes it back that shouldn't be padded. Also if the response is anything else than echo reply you also should not pad. However, I think the implication is the same either way. Both masque client and server need to send ICMP or modify its ICMP processing. Given that I would think having each endpoint doing independent processing of its forward path might actually be simpler and enables using a standard off the shelf ICMP implementation and not have to modify it.

**Comment by achernya** [comment]
Our implementation has userspace ICMP request/response handling for echo request/response, it wasn't too hard to write. I don't propose modifying anything, but the structures were ~50 lines of code to set up. I agree we shouldn't be modifying responses we did not generate.

**Comment by tfpauly** [comment]
I think the existing text already is generic to "endpoint", not client or server:

> CONNECT-IP endpoints can also send ICMPv6 echo requests with 1232 bytes of
> data to ascertain the link MTU and tear down the tunnel if they do not receive
> a response. Unless endpoints have an out of band means of guaranteeing that
> one of the two previous techniques is sufficient, they MUST use this method.

So this implies that both sides need to send the PING if they haven't guaranteed the MTU. This seems like this is already handled?

**Comment by gloinul** [comment]
> I think the existing text already is generic to "endpoint", not client or server:
> 
> > CONNECT-IP endpoints can also send ICMPv6 echo requests with 1232 bytes of
> > data to ascertain the link MTU and tear down the tunnel if they do not receive
> > a response. Unless endpoints have an out of band means of guaranteeing that
> > one of the two previous techniques is sufficient, they MUST use this method.
> 
> So this implies that both sides need to send the PING if they haven't guaranteed the MTU. This seems like this is already handled?

If both endpoints are required to send ping it would be resolved. However, that is not what is written in the draft currently. What is written is the there are various techniques, and if an endpoint choses something else than verifying its forward path using ping, it becomes unclear who is actually responsible for any HTTP intermediaries. Which results in an unclear requirement and very likely failure of the MTU verification resulting in an MTU black hole.

**Comment by tfpauly** [comment]
Well, it does say that endpoints MUST use this method unless the already have other coordination. I could see some clarification text to say that the guarantee for the other methods must include knowing there isn't an intermediary — which is actually pretty easy to guarantee in many cases.
