### ISSUE TITLE
What do if a tool small link MTU is detected?

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-connect-ip#62]
I think there are two option here, 1) close/deny the connect request, and 2) use streams instead. I think we should consider both option, especially given stream are just there to use.

**Comment by tfpauly** [comment]
Isn't this a dup of #45? That's fixed with #60.

I guess the text could be generalized to talk about more than just IPv6 MTU issues.

**Comment by gloinul** [comment]
> Isn't this a dup of #45? That's fixed with #60.

No, this aspect on what you do when the MTU required is not present is not resolved by that PR. I would note that closing gives the endpoints one experience that is likely easier to handle in implementation and do avoid the issue with reordering and the varying packet treatment that moving to stream would result.

**Comment by DavidSchinazi** [comment]
I would suggest adding a sentence saying that if an endpoint realizes that the IPv6 tunnel MTU goes lower than 1280, then it MUST close the stream.

**Comment by ekinnear** [comment]
IETF 114: Note that if something happens and your MTU gets smaller, you may need to kill that link.
