### ISSUE TITLE
What the right ICMP or other kind of error response if the client uses an unassigned/wrong source IP?

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-connect-ip#64]
Based on the discussion in issue #43 we recommend to use ICMP for error signal. ICMP works for MTU issue or destination unreachable, however, there is no appropriate message type if the IP header of the packet provided by the client contains an IP that wasn't assigned to the client. So we need a different kind of error handling for this case?

**Comment by mirjak** [comment]
I guess that could do it. Should we be more specific in the draft?

Also, we probably would need to be more explicit in the draft that you should request a scope for your CONNECT request that allows you to received ICMP messages.

**Comment by DavidSchinazi** [comment]
Can you write a PR for this please?

**Comment by ekinnear** [comment]
IETF 114: Recommend including ICMP if providing routes to the peer, and clients should always be prepared to receive ICMP.

Also add note that ICMP may have other source/destination addresses so as to not surprise endpoints.

> At minimum, always get ICMP on point to point link, regardless of IPPROTO. If you want to guaratnee that you get everything, you have to request ICMP specifically. However, proxy MAY be aware of the 5-tuples and forward it for you.

**Comment by ekinnear** [comment]
Also look at RFC 4301 for some potentially helpful text.
