### ISSUE TITLE
Should there be a way to say "please assign me an address but I don't care which" ?

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-masque/draft-ietf-masque-connect-ip#66]
Implementing this on the client I was wondering if there should be a way for the client to ask for the server for an address without specifying what address it wants. This could allow a VPN client to mention that it wants an IPv6 address or not.

If we think this could be useful, we could encode it as `ADDRESS_ASSIGN(IPv4-0.0.0.0/32)` or `ADDRESS_ASSIGN(IPv6-::/128)`.

**Comment by achernya** [comment]
I believe asking for the Any address is what we discussed previously, so +1

**Comment by gloinul** [comment]
You mean ADDRESS_REQUEST(IPv4-0.0.0.0/32) don't you. I think the format of the request works fine. But we do need to resolve #54 before we implement this into the specification.

**Comment by tfpauly** [comment]
Yes — if we have this, one option is to _always_ have an ADDRESS_REQUEST expected from clients, and then there doesn't need to be signaling. Or we do the simple solution to 54 to say "I expect to send N capsules with my request".

**Comment by DavidSchinazi** [comment]
You're right this could be a potential solution to #54. Let's discuss them together tomorrow

**Comment by gloinul** [comment]
Regarding IPv6, I think a standard request that would make sense is asking for any /64. I guess that works fine with this idea too?

**Comment by DavidSchinazi** [comment]
Oh that's interesting, if the IP Address is `0.0.0.0` or `::`, the prefix length is a hint for the requested length. I like that.

**Comment by ekinnear** [comment]
IETF 114: Add an editorial sentence to "remember, what you ask for may not be what you get, especially with regards to address families".
