### ISSUE TITLE
Clarify that ICMP may be received at any time

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ip#71]
If one is using IPPROTO to select a particular protocol to be tunneled, one may still received ICMP in the context of this request. To my understanding there are two reasons for this.

a) ICMP generated by the Connect-IP peer endpoint
b) ICMP sent back by node beyond the Connect-IP that is directly related to forward traffic sent by this endpoint and which the tunnel endpoint maps back to the Connect-IP request. 

I think we could add a clarification of this in #69, or we could do it later.

**Comment by DavidSchinazi** [comment]
Totally agree. I added fb1578626de4d3073ac31f5cb89c06efae2ebc51 to address this as part of #69.
