### ISSUE TITLE
Save some space and error checking

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-masque/draft-ietf-masque-connect-ip#72]
Splitting {ADDRESS_REQUEST|ADDRESS_ASSIGN|ROUTE_ADVERTISEMENT} into ..._V4 and ..._V6 would result in smaller capsules that have fewer error conditions.  It would also keep IPv4 and IPv6 logic distinct.

**Comment by DavidSchinazi** [comment]
I don't think the size of these capsules matters given their rarity. I can see the error condition argument but it's pretty minor and would come at the cost of making the specification longer. I don't feel too strongly here, but I think I have a slight preference for keeping things as they are.

**Comment by mirjak** [comment]
I agree with David that size is problem not a big concern. I think having one set of capsule is less complex.

**Comment by tfpauly** [comment]
I also have a preference for keeping the capsules as they are with versions included; it also allows the route advertisement capsule to include routes for both v4 and v6 in one capsule, which I think is very important. I wouldn't want to lose that feature.

**Comment by achernya** [comment]
I similarly have a preference for keeping v4 and v6 in one capsule and agree size is not a big concern.

**Comment by achernya** [comment]
I just chatted with @martinthomson to see what error conditions he was thinking of. Upon discussion (v6 route advertised when only v4 address is available), we concluded that this is not an error case, it's just a route that's not *yet* usable. We've concluded that this is something that we're comfortable leaving as-is.
