### ISSUE TITLE
Well-known IANA registration

### ISSUE THREAD

**Issue by gloinul** [ietf-wg-masque/draft-ietf-masque-connect-ip#81]
Have we checked with the expert @mnot what the preferred way of documenting that multiple document specify different part of the sub-path after the initial prefix? 

I would feel that we need to be clearer that we want IANA to add this information to what is already existing. The use of just update can easily mean replace which would not be correct. I also wonder if this should be an additional entry line or just kept in the same entry is unclear to me. I could see that one actually split the current masque entry into two, one for masque/udp and one for masque/ip

**Comment by gloinul** [comment]
So for clarity this is about this section: 
https://ietf-wg-masque.github.io/draft-ietf-masque-connect-ip/draft-ietf-masque-connect-ip.html#name-updates-to-masque-well-know

**Comment by tfpauly** [comment]
I imagine this should imitate what CONNECT-UDP published for its RFC?

**Comment by gloinul** [comment]
@tfpauly the issue I see her is the fact that UDP and IP tries to share the same well known suffix of "masque". So the question that arises here is how we are tracking the sub-identifiers and their references in this registry. So UDP created this registry, but does not specify a sub-registry, if it did that would be the registry we would add "ip" to. Instead it appears the current intention are adding both references into the same registry entry. And if we are doing that we need to be more careful in our instructions to IANA. A third way forward would be to register "masque/ip" as the well known suffix and get a separate entry into the table. 

https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml

I also think we haven't discussed this much, and I think we should rope in the expert into this discussion. I think we will have to move to email for that. But I want to check with the other authors first, I think we especially want @DavidSchinazi thoughts here about it. I am willing to drive the question towards the MASQUE WG, the IANA expert (Mark Nottingham) and I assume it is HTTPBIS WG that might have additional input into this.

**Comment by mnot** [comment]
The registry cannot and will not allow strings like `masque/ip` -- the only registrable string is what's legal as a path segment.

Managing the space "under" the registered path segment is up to the registrant. You could create a sub-registry, or you could just update the registering document when you need to expand it.

**Comment by gloinul** [comment]
Thanks @mnot thus I think this is an issue we need to take to the MASQUE WG to discuss how to bet handle and if there should be put in place some additional registries under the masque suffix.

**Comment by gloinul** [comment]
Started discussion on the masque mailing list: https://mailarchive.ietf.org/arch/msg/masque/6oBDmogCWG6mILKhwa_ea2flwQM/
