### ISSUE TITLE
Text on ICMP

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-connect-ip#82]
This is the current text in the draft

> If an endpoint sends ROUTE_ADVERTISEMENT capsules, its routes SHOULD include an allowance for receiving ICMP messages. If an endpoint does not send ROUTE_ADVERTISEMENT capsules, such as a client opening an IP flow through a proxy, it SHOULD process proxied ICMP packets from its peer in order to receive these errors. Note that ICMP messages can originate from a source address different from that of the CONNECT-IP peer.

However, this seems to be mixing two things: ICMP messages directly from the proxy or other ICMP messages from any host behind the proxy.

I think the main thing we want to say here is that even when he client didn't request proxying of ICMP messages, it might get ICMP messages directly from the proxy and should process them.

If the proxy should forward any ICMP messages from other hosts to the client is a separate question. I would actually say the answer should be no, expect if requested by the client.

**Comment by tfpauly** [comment]
We definitely need to allow for ICMP from the peer itself.

I imagine the client should also gracefully handle receiving ICMP received from some other address, though? If the proxy receives an ICMP error from a host upstream on particular IP flow that the client did request, why not have it forward along the error? The client can decide what to do for processing at that point.

**Comment by DavidSchinazi** [comment]
+1 to what Tommy, said: we should allow ICMP that doesn't come from the peer. The text currently states that. I propose to close with no action

**Comment by mirjak** [comment]
What I saying it that I think receiving ICMP from the masque proxy is a MUST (because this is the only error handling we have) while receiving other ICMP is a should.

Also we do have a mechanism for the client to actually request ICMP scope. That means the client can tell the proxy if it wants to receive those ICMP or not. Why not using it?

**Comment by achernya** [comment]
I'm not sure what text changes you're proposing, @mirjak. By my read the current text is fine, although we disagree on MUST versus SHOULD. I think receiving ICMP from the masque proxy is a SHOULD, because it's still possible to successfully pass packets if you ignore ICMP. Also we already have a mechanism to request an ICMP scope with the ipproto restriction. In general on the internet we send ICMP no matter what, and if some firewall on-path wants to drop (silently or with notification), that's up to them.

**Comment by DavidSchinazi** [comment]
+1 to what Alex said, dropping ICMP is common, so even if we were to use `MUST`, it would be an RFC 6919 `MUST (BUT WE KNOW YOU WON'T)`. `SHOULD` is more realistic
