### ISSUE TITLE
Example inconsistencies

### ISSUE THREAD

**Issue by asedeno** [ietf-wg-masque/draft-ietf-masque-connect-ip#90]
In the examples section (8), `ADDRESS_ASSIGN` capsules do not have individual `Assigned Address` entries wrapped in parenthesis, unlike the otherwise identically spec'd `IP Address Range` entries in a `ROUTE_ADVERTISEMENT` capsule. This feels especially odd in example 8.3 where two addresses are assigned. Should we just wrap them everywhere?

The example `Assigned Address` entries do not contain a `Request ID`. We should include this value, and perhaps add another example with an `ADDRESS_REQUEST` capsule so every example address doesn't carry a zero-value `Request ID`.

**Comment by DavidSchinazi** [comment]
Closed by #92

**Comment by asedeno** [comment]
#92 took care of the trivial bits; we may still want an example with an `ADDRESS_REQUEST`, though that can be broken out into a separate issue if desired.

**Comment by DavidSchinazi** [comment]
@asedeno could you break that into a separate issue please? Or ideally a PR? :)
