### ISSUE TITLE
Lifetime of the IP tunnel

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-ip#97]
> The lifetime of the IP forwarding tunnel is tied to the IP proxying request stream. Closing that stream (in HTTP/3 via the FIN bit on a QUIC STREAM frame, or a QUIC RESET_STREAM frame) closes the associated IP tunnel.

I think it would be helpful to review the lifetime text in https://www.rfc-editor.org/rfc/rfc9298#section-3.1-5 more closely align with it where it makes sense. What stuck out to me first was speaking about HTTP/3 specifically sticks out because all versions are supported. Second, there's no text about if a proxy can timeout itself and close the stream.

**Comment by DavidSchinazi** [comment]
This makes sense, we can be a bit more specific with this guidance
