### ISSUE TITLE
No examples in section 4

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-ip#98]
Our cousin, CONNECT-UDP, has simple examples about how the requests and responses look in HTTP/1.1, 2 and 3. 

I appreciate the appendix has complicated examples. Would it be worth providing simple examples in Section 4, or at least forward referencing to them so people can get a feel?

**Comment by DavidSchinazi** [comment]
That would be nice, if someone's willing to volunteer to do the editorial work of writing that PR. In other words, I'll happily review and merge it, but I don't have time to write it personally.

**Comment by LPardue** [comment]
there's 5 authors on the draft, maybe one of the other 4 can spare the 10 minutes it would take?

**Comment by tfpauly** [comment]
Simple enough to add =)
