### ISSUE TITLE
Change the Capsule type values prior to publication

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-masque/draft-ietf-masque-connect-ip#99]
https://www.ietf.org/archive/id/draft-ietf-masque-connect-ip-05.html#name-capsule-type-registrations registers 3 capsules that use 0x1ECA6A00, 0x1ECA6A01, and 0x1ECA6A02. Its good practice to use the provisional registration space while developing a document, so you have my appreciation. But its not clear if you intend to change these into the permanent registration space prior to publication. CONNECT-UDP followed that approach and noted it with `(note that this will switch to a lower value before publication)`.

Please clarify if you intend to change the values and, if so, when.

**Comment by DavidSchinazi** [comment]
That's a good point, I was planning on changing them right after WGLC but I guess that's not written in the draft. Let's keep this issue open during the WGLC and close it once we move to the final values

**Comment by DavidSchinazi** [comment]
Plan is to have:
* 0x01 for ADDRESS_ASSIGN
* 0x02 for ADDRESS_REQUEST
* 0x03 for ROUTE_ADVERTISEMENT
assuming @LPardue agrees since we're the two IANA experts on that registry

**Comment by LPardue** [comment]
in principle that's fine by me. We should be wary of using them too early in case things have to change even after WGLC. So late binding once publication is impending is the least risky and works for me.

**Comment by DavidSchinazi** [comment]
On one hand I agree with you that assigning them sooner avoids the risk of dealing with interop failures if IESG review leads to unavoidable wire-format changes. On the other, waiting until after IESG approval means that now we have interop issues between the folks that deployed before or after that - that's what we're seeing with QUIC version negotiation. So I would prefer to get provisional registrations for the low codepoints after WGLC personally

**Comment by LPardue** [comment]
reasonable
